### PR TITLE
Change syntax hightlight notation from md to html

### PR DESCRIPTION
**Pull request by bleis-tift**
[Query Expressions (F#) Page](https://msdn.microsoft.com/visualfsharpdocs/conceptual/query-expressions-%5bfsharp%5d) does not highlight code snipets in table.
So I change notation from markdown to html.

### CODE REVIEW

**Comment by cartermp** [comment]
LGTM.  @dend will changing the table from `.md` to `.html` be good for the site?

**Comment by dend** [comment]
Where is the `lang-fsharp` class coming from? In the rendered HTML I see `hljs fsharp`. @bleis-tift

**Comment by bleis-tift** [comment]
@dend I checked it by [chrome feature(right click and view source)](view-source:https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/query-expressions-%5Bfsharp%5D).
`<pre><code class="lang-fsharp">query { expression }</code></pre>` it is in line 6298-6299.

**Comment by dend** [comment]
Let's try this. First, resolve the conflicts with the current branch and I will merge this.

**Comment by dend** [comment]
And lift-off.

**Comment by dend** [comment]
Awesome, looks like it worked. Thanks @bleis-tift 🔥

**Pull request merged**
