### PR TITLE
Add Array.chunkBySize documentation

### PR DESCRIPTION
**Pull request by Banashek**
Regarding #188 : It looks like there are GUIDs generated for the links in the module documentation. Is this link something I should be including in these commits, or is it auto-generated on build?

Also feel free to squash these commits. I'm still figuring out how Github PRs work.

### CODE REVIEW

**Comment by Banashek** [comment]
Related to #184

**Comment by KevinRansom** [comment]
@Banashek , hey thanks for doing this.  It looks good, but I sort of think that:
__Divides the input array into chunks of size at most chunkSize.__  is slightly awkward.

I wonder if:
Divides the input array into chunks of  consisting of chunkSize elements.  The last chunk may contain fewer thank chunkSize elements.

or some variation would be a bit more specific.

What do you think?

Kevin

**Comment by cartermp** [comment]
@KevinRansom Agreed, however, this is also the exact text used in the API itself: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/list.fsi#L64

We could make a PR to FSharp.Core to update that text as well.

**Comment by KevinRansom** [comment]
Indeed.

**Comment by dend** [comment]
@Banashek what GUIDs are you referring to? Also, no worries about multiple commits - that doesn't make much of a difference for us 🔥

**Comment by Banashek** [comment]
@KevinRansom Yeah that was a copy/paste from the .fsi file

@dend The actuall collections.array-module-\[fsharp\].md file seems to have guid links to the other pages. The issue appears to state that the missing links for the various `Contains` methods are missing. I don't know where the guids are created from.

Here is a sample line from that file:
```
|[`append`](https://msdn.microsoft.com/library/08836310-5036-4474-b9a2-2c73e2293911)<br />**: 'T [] -&gt; 'T [] -&gt; 'T []**|Creates an array that contains the elements of one array followed by the elements of another array.|
```

Specifically the "https://msdn.microsoft.com/library/08836310-5036-4474-b9a2-2c73e2293911" link

**Comment by Banashek** [comment]
Also @KevinRansom regarding the descriptions, I was working on Seq.chunkBySize which has almost the same definition.

In that case I think that it's a bit misleading, since Seq.chunkBySize returns a sequence that when enumerated returns arrays of size `chunkSize`.

I'm not sure if I should put the updated explanation in the PR or wait for it to be changed in the core repo first.

What is your opinion on this?

**Comment by KevinRansom** [comment]
Make the change in the docs and also submit a PR to the code repo. ☺

**Comment by dend** [comment]
@Banashek ah, gotcha. The GUID is an internal identifier for us and should redirect to the proper "short ID" page. If you want to reference any other MSDN page, feel free to include the links the same way you see it in the browser, just remove the locale and make sure you're using the HTTPS version.

**Comment by Banashek** [comment]
Locales removed

**Comment by Banashek** [comment]
Is this PR on hold waiting for a PR to be accepted to Fsharp.Core?

I don't mind submitting the PR over there, just wanted to check.

**Comment by cartermp** [comment]
LGTM.

@Banashek Nope!  Feel free to submit the PR to visualfsharp at any time.

**Comment by dend** [comment]
Thanks for your contribution! We are currently in the process of moving F# documentation to docs.microsoft.com and therefore are instituting a PR freeze. Once the migration is complete, we will be able to integrate your change.

FYI: @cartermp @KevinRansom

**Comment by dend** [comment]
Thank you for your contribution! We are no longer accepting pull requests in this repo. Please continue your work in our docs.microsoft.com F# repository - you can see all of that documentation [here](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/).

**Pull request closed without merging**
