### PR TITLE
Doc fixes.

### PR DESCRIPTION
**Pull request by dend**

### CODE REVIEW

**Comment by cartermp** [comment]
LGTM

**Comment by dend** [comment]
@cartermp I won't approve this one yet because I am working on bot validation logic against our docs :-) Hence need this PR to be open.

**Comment by cartermp** [comment]
Sounds good!

**Comment by smoothdeveloper** [comment]
Bots coming, exciting! :)

**Comment by dend** [comment]
@smoothdeveloper I am testing some validation right now :)

**Comment by dend** [comment]
IT WORKS!

**Comment by dend** [comment]
LGTM

**Comment by cartermp** [comment]
LGTM

**Pull request merged**
