### PR TITLE
Doc fixes.

### PR DESCRIPTION
**Pull request by dend**

### CODE REVIEW

**Comment by KevinRansom** [comment]
The changes look great.

However, if the correct style for keywords is slightly shaded code boxes, then there are a couple of actual bolds that probably should fixed on the same page:

E.g.  
1.   The myStaticValue  in this text:

The following static property definition is based on a scenario in which you have a static field myStaticValue that is the backing store for the property.

2.  let and do in this text:
, just like let bindings and do bindings in a type definition. 

3. Perhaps set in this text.
You can set properties that provide set accessors by using the <- operator.

4.  and 20 in the output here:
The output is 20.

**Comment by dend** [comment]
@KevinRansom just committed another change that should fix that. Thanks for the heads-up!

**Comment by KevinRansom** [comment]
let and do are still bold in this text: , just like let bindings and do bindings in a type definition. 

Also I see this text when I view:
You can set properties that provide  set  accessors by using the  &lt;-  operator.

**Comment by dend** [comment]
@KevinRansom fixed!

**Comment by KevinRansom** [comment]
This looks great, thanks Den, you are doing a brilliant job.

Thank you,

Kevin

**Pull request merged**
