### PR TITLE
Fixes to errors in #194

### PR DESCRIPTION
**Pull request by liboz**
Fixes to errors in #194

### CODE REVIEW

**Comment by dend** [comment]
So you are replacing `seq<'T>` with `'T`?

@cartermp @KevinRansom - can you please sign-off on the change?

**Comment by liboz** [comment]
I'm replacing `seq<'T>` with `'T list `

**Comment by cartermp** [comment]
Yep, this LGTM.

**Comment by dend** [comment]
LGTM

**Pull request merged**
