### PR TITLE
Remove silverlight and fix lib references

### PR DESCRIPTION
**Pull request by dsyme**
There are many problems with the Visual F# docs.  This addresses a couple I spotted on first glance

- removes most mentions of Silverlight 

- Calling FSharp.Core the "main" F# library instead of the "core" library

@dend - I've added a link to http://fsharp.org/community/projects.  Is it allowed to have links to non-Microsoft sites in these docs? Thanks

### CODE REVIEW

**Comment by KevinRansom** [comment]
Yes … we can now power forward with improvements to the documentation.  And it is a fertile soil for bug fixes.

Kevin

**Comment by dend** [comment]
@dsyme it should be fine, however I would recommend using https://aka.ms links to make sure that we can easily swap them when necessary.

**Comment by dsyme** [comment]
Could you add a README.md with info on how to create aka.ms links, guidelines etc? Thanks

**Comment by dend** [comment]
@dsyme this should be for internal-only. Just go to aka.ms, log in with your corp creds and create a new link. If we see community contributions that point to external links, we should just convert them to aka.ms ourselves **or** automate the process with a build agent.

**Pull request merged**
