### PR TITLE
Update seq.map['t,'u]-function-[fsharp].md

### PR DESCRIPTION
**Pull request by a688**
Add example to page

### CODE REVIEW

**Comment by dend** [comment]
@a688 could you please revert the two lines that you removed? I will add the right metadata there.

**Comment by a688** [comment]
Done. How does that look?

**Comment by smoothdeveloper** [comment]
@a688 two minor remarks:

* can we use some other name "simpleArray" -> "simpleSeq" maybe?
* add fsharp right after the triple backquotes to make the snippet's language explicit

LGTM otherwise!

**Comment by dend** [comment]
Looks good, thank you!

**Pull request merged**
