### PR TITLE
Change from GUID to relative links

### PR DESCRIPTION
**Pull request by liboz**
Fixes the things brought up in #188 and #226

### CODE REVIEW

**Comment by dend** [comment]
@liboz build has link warnings - can you please URL-encode the file names referenced?

**Comment by liboz** [comment]
@dend Aren't those from the preexisting GUID urls in the file? I copied the style that's in the TOC.md file. 

If it's because of my change, do you want me to change the links to something like: 
`(https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/seq.tail['t]-function-[fsharp])`

 As opposed to:
 `(seq.tail['t]-function-[fsharp].md)`

**Comment by dend** [comment]
@liboz sorry, to be clear - URL encode this: `seq.tail['t]-function-[fsharp].md`, so it is `seq.tail%5B't%5D-function-%5Bfsharp%5D.md`

**Comment by dend** [comment]
Looks like there are some conflicts @liboz 

Can you please resolve those, and I will merge?

**Pull request merged**
