### PR TITLE
Add Array.chunkBySize docs

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR adds the documentation for `Array.chunkBySize`.

Refs #184

### CODE REVIEW

**Comment by dend** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/conceptual/collections.array-module-[fsharp].md](https://github.com/ErikSchierboom/visualfsharpdocs/blob/array-chunkbysize-docs/docs/conceptual/collections.array-module-[fsharp].md) | :warning:Warning | | [Details](#user-content-docs/conceptual/collections.array-module-[fsharp].md)
[docs/conceptual/array.chunkbysize['t]-function-[fsharp].md](https://github.com/ErikSchierboom/visualfsharpdocs/blob/array-chunkbysize-docs/docs/conceptual/array.chunkbysize['t]-function-[fsharp].md) | :white_check_mark:Succeeded | |
[docs/conceptual/snippets/fsarrays/snippet75.fs](https://github.com/ErikSchierboom/visualfsharpdocs/blob/array-chunkbysize-docs/docs/conceptual/snippets/fsarrays/snippet75.fs) | :white_check_mark:Succeeded | |

<a name="docs/conceptual/collections.array-module-[fsharp].md"></a>
### [docs/conceptual/collections.array-module-[fsharp].md](https://github.com/ErikSchierboom/visualfsharpdocs/blob/array-chunkbysize-docs/docs/conceptual/collections.array-module-[fsharp].md)
 - **Line 41**: **[Warning]** Invalid file link:(~/array.chunkBySize[&amp;#39;t%5D-function-%5Bfsharp%5D.md).
 - **Line 43**: **[Warning]** Invalid file link:(~/array.comparewith[&amp;#39;t%5D-function-%5Bfsharp%5D.md).
 - **Line 45**: **[Warning]** Invalid file link:(~/array.contains[&amp;#39;t%5D-function-%5Bfsharp%5D.md).
 - **Line 47**: **[Warning]** Invalid file link:(~/array.countby[&amp;#39;t,&amp;#39;key]-function-[fsharp].md).
 - **Line 49**: **[Warning]** Invalid file link:(~/array.distinct[&amp;#39;t%5D-function-%5Bfsharp%5D.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C12%5C2de48aa7-d89a-b079-f888-888d32c75daf%5CPullRequest%5C201703120915262216-273%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eriawan** [comment]
Hi @dend 

CMIIW, any PR to this repo should be no longer valid, right? as far as I know, we are focusing on docs.microsoft.com F# docs.

**Comment by ErikSchierboom** [comment]
@eriawan Oh, sorry about that, but I responded to a Tweet from the visualfsharpteam that tried to enlist help with their documentation and they linked to this repository.

**Comment by eriawan** [comment]
@ErikSchierboom no worries :)

I know that VisualStudio F# team is tweeting the needs for contribution to F# docs. Please continue your PR to this repo, Erik. 
There are still warnings on the PR you have submitted. So I think let's finish your PR on this repo first. I'm sure @dend will be glad to help you to update the docs on MSFT Docs based on your approved PR.

**Comment by cartermp** [comment]
Actually, this PR is valid.  More generally, anything under FSharp.Core is valid because those docs have no yet migrated to docs.microsoft.com.  We're in the process of building out a newer and better API Reference browser which dramatically improves the experience today.

@KevinRansom we should be clear that there is a split in documentation for F# at the moment, where API Reference material lives here, and the conceptual F# Guide material loves on docs.microsoft.com.

**Comment by cartermp** [comment]
LGTM

**Comment by eriawan** [comment]
@cartermp ok, I understand now. 

I was confused before, because the tweet refers to this repo but there are some docs already in F# section on Docs. We should change the README.MD file to indicate that this repo is for documenting F# API, while F# section on MSFT Docs is for conceptual just like you said.
@ErikSchierboom apologies for any confusion I may have caused. @cartermp has given the clarification.

**Comment by ErikSchierboom** [comment]
@eriawan No problem!

**Pull request merged**
