### PR TITLE
Wrong argument order.

### PR DESCRIPTION
**Pull request by ReverseBlade**

### CODE REVIEW

**Comment by dend** [comment]
Thanks for your contribution! We are currently in the process of moving F# documentation to docs.microsoft.com and therefore are instituting a PR freeze. Once the migration is complete, we will be able to integrate your change.

FYI: @cartermp @KevinRansom

**Comment by eriawan** [comment]
@dend @cartermp 
Just curious, because some new issues hasn't been answered. 
Has the migration completed? Any estimation on the migration?

**Comment by cartermp** [comment]
@eriawan It's still in-progress.  I'm organizing content according to [this issue](https://github.com/dotnet/core-docs/issues/834) and testing things on a staging server.  Once things like links all work, I'll push the test branch to live so we can see it live and start accepting PRs on the [dotnet/core-docs](https://github.com/dotnet/core-docs) repo.  We're still in the process of figuring out how moving the FSharp.Core API reference is going to work.  There are a few unanswered questions that the entire docs.microsoft.com site as to answer for API reference material, such as having a good contribution story for remarks and code samples.

**Comment by dend** [comment]
Thank you for your contribution! We are no longer accepting pull requests in this repo. Please continue your work in our docs.microsoft.com F# repository - you can see all of that documentation [here](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/).

**Pull request closed without merging**
